server:
  error:
    include-stacktrace: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chessdb
    username: admin
    password: admin
    show-sql: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true