spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chessdb                                  █
    username: admin                                                           █
    password: admin